apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: flyimg
  name: docker-app
spec:
  tags:
  - annotations:
      openshift.io/imported-from: flyimg/docker-app
    from:
      kind: DockerImage
      name: flyimg/docker-app
    name: latest
